### ISSUE TITLE
Still Odia language not showing

### ISSUE THREAD

**Issue by soumendrak** [tracestrack/openstreetmap-localization-tool#15]
I have made a Pr #14 to add Odia language. It has been merged as well. However, it is not showing on the website. What else needs to be done here?

**Comment by quinncnl** [comment]
Hi, looks like the build failed with github action build. Checking

**Comment by quinncnl** [comment]
Hi @soumendrak it's fixed now. Right now it uses github pages for hosting. I'll move it to cloudflare pages to have the automatic release. (right now it's manual)

**Comment by soumendrak** [comment]
Thanks a lot.
